spring.application.name=stock

#1
##SQL Server 1433 -express april-21-2025
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CanadaAT;encrypt=true;trustServerCertificate=true;
#spring.datasource.username=sa
#spring.datasource.password=root123
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver


#2
##Mysql-3306
#spring.datasource.url=https://localhost:5500/em
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#3
##PostGres-5432
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=RaDeKeLa@#09
#spring.datasource.driver-class-name=org.postgresql.Driver


#4
##MariaDb-3307
#spring.datasource.url=jdbc:mariadb://localhost:3307/canadaat_uq
#spring.datasource.url=jdbc:mariadb://localhost:3307/stock_test
#spring.datasource.url=jdbc:mariadb://localhost:3307/canat
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


#5
#Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:5500/orcl
spring.datasource.username=system
spring.datasource.password=root123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate configurations
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#6
#spring.datasource.url=jdbc:h2:mem:mytestdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=true
#spring.h2.console.enabled=true

#6
##MongoDb

#7
##CosmosDb

#8
##DynamodB

#9
##Cassendra

#10
##VectorDb


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#server.port=8443
#server.port=8444
#server.port=8445
server.port=8446
#server.port=8448
#server.port=9000
springdoc.show-actuator=true

DEBUG com.zaxxer.hikari.pool.HikariPool -HikariPool-1 - Timeout failure stats (total=1, active=1, idle=0, waiting=0)


security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
## 24h in millisecond
#security.jwt.expiration-time=86400000
#30days
#security.jwt.expiration-time=2592000000

#365 days
security.jwt.expiration-time=31536000000

server.ssl.key-store=C:/Users/pavan oruganti/Downloads/keystore/stock.jks
server.ssl.key-store-password=root123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=stockproject